# Generated by Django 5.2.7 on 2025-11-03 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=10, unique=True, verbose_name='Cédula')),
                ('nombres', models.CharField(max_length=100, verbose_name='Nombres')),
                ('apellidos', models.CharField(max_length=100, verbose_name='Apellidos')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Correo Electrónico')),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha de Nacimiento')),
                ('carrera', models.CharField(choices=[('ISW', 'Ingeniería de Software'), ('ISI', 'Ingeniería en Sistemas'), ('IEC', 'Ingeniería en Computación'), ('ITE', 'Ingeniería en Telecomunicaciones')], max_length=3, verbose_name='Carrera')),
                ('semestre', models.IntegerField(verbose_name='Semestre')),
                ('promedio', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Promedio')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
            ],
            options={
                'verbose_name': 'Estudiante',
                'verbose_name_plural': 'Estudiantes',
                'ordering': ['-fecha_registro'],
            },
        ),
    ]
